### PR TITLE
Create struture Translate NIP-0001 for Brazilian Portuguese

### PR DESCRIPTION
**Pull request by EvertonMelo**
start of the translation of NIP-0001 To Portuguese of Brazil.
#partial translation.

### CODE REVIEW

**Comment by EvertonMelo** [comment]
hi guys, 
@dgarcia360 @aleixmorgadas 
you can help me?

**Comment by aleixmorgadas** [comment]
Hi @EvertonMelo , I've some comments about the pull request.

1. It's not a full translation to Portuguese of Brazil. We cannot accept a non-complete pull request.
2. It's a draft NIP, it may change in the future a little. Consider waiting until we have the final version.

Because of the nature of NIP repository, we are more rigorous in the contributions compared to other projects.

**Comment by EvertonMelo** [comment]
@aleixmorgadas 

for their comments.

1 - I have nowhere found a definite translation policy, so I sent what I had, to negotiate an appropriate way to do that. 

2.1 - _It's a draft NIP, it may change in the future a little._
Resp: yes I agree, but I see that creating a repository for location and deduplication will only give the main project more power. As for the content change is just to inform on what date the document was made, server documentation to make the content but understandable if it forms in the native language even better.

2.2: Consider waiting until we have the final version.
R: I would do it if there was a timeline, a deadline or even a flow, but there is clearly that, which I have only STATUS.

**Comment by aleixmorgadas** [comment]
> 1 - We cannot accept a non-complete pull request.
> Resp: I have nowhere found a definite translation policy, so I sent what I had, to negotiate an appropriate way to do that.
>
> 2.1 - It's a draft NIP, it may change in the future a little.
> Resp: yes I agree, but I see that creating a repository for location and deduplication will only give the main project more power. As for the content change is just to inform on what date the document was made, server documentation to make the content but understandable if it forms in the native language even better.

We haven't a "policy" for translations but makes sense to be a complete translation. I agree with you that make it more understandable it's better, no doubt here. Let's agree with the next points:

1. Make a complete translation
2. It has to be reviewed by at least 2 more people to make sure the translation is made properly.
3. Merge PR

About point 2, we required 5 people reviewing the initial document to make sure we hadn't erratas and everything was OK. The document is long, that's why I recommend two more people verify the content.

> 2.2: Consider waiting until we have the final version.
> R: I would do it if there was a timeline, a deadline or even a flow, but there is clearly that, which I have only STATUS.

It may change, but it shouldn't be big changes. For me it's almost definitive, the changes will be little or none. It's OK for start translating.

@EvertonMelo , thank you for spending your time in NEM :)

**Comment by EvertonMelo** [comment]
@aleixmorgadas 

Thank you for your feedback.

[I'm start item 1](https://github.com/NemProject/NIP/pull/1/commits/d121b027de03ef4a18e8e8c84cb3baacebbf4da6). 

as for review, it is a question of time and goodwill.

as for the number of translators, this is not necessary since the code has always been open and no one before me has done the translation.

**Pull request closed without merging**
